---
- name: Execute the Ligthing scenario in grenoble
  hosts: grenoble

  tasks:
    - include: experiment.yml
      vars:
        SITE: grenoble
        SENSORS_N: 100
        BORDERS_N: 5
        SERVERS_N: 3
        DURATION: 10090
        PACKET_LENGTH: 30
        EXP_PARAMETER: 0.00208
        PERIOD_PARAMETER: 0.0
        GENERATION_TYPE: EXPONENTIAL
        ZSTD_VERSION: 1.4.9