---
- name: Execute the HVAC scenario in grenoble for 1 hour
  hosts: grenoble

  tasks:
    - include: "{{ lookup('env', 'BASE_EXPERIMENT') }}"
      vars:
        SITE: grenoble
        SENSORS_N: 100
        BORDERS_N: 5
        SERVERS_N: 3
        DURATION: 60
        PACKET_LENGTH: 60
        EXP_PARAMETER: 0.0
        PERIOD_PARAMETER: 260
        GENERATION_TYPE: PERIODIC
        ZSTD_VERSION: 1.4.9
