---
- name: Execute the Surveillance scenario in strasbourg
  hosts: strasbourg

  tasks:
    - include: "{{ lookup('env', 'BASE_EXPERIMENT') }}"
      vars:
        SITE: strasbourg
        SENSORS_N: 30
        BORDERS_N: 5
        SERVERS_N: 3
        DURATION: 10090
        PACKET_LENGTH: 127
        EXP_PARAMETER: 0.0
        PERIOD_PARAMETER: 0.01016
        GENERATION_TYPE: PERIODIC
        ZSTD_VERSION: 1.4.9