name: "Run the experiments"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - name: Build the scripts
      run: nix build
    - name: set secrets
      env:
        FITIOT_USER: ${{ secrets.FITIOT_USER }}
        FITIOT_KEY: ${{ secrets.FITIOT_KEY }}
        STREAM_USER: ${{ secrets.STREAM_USER }}
        STREAM_HOST: ${{ secrets.STREAM_HOST }}
        STREAM_KEY: ${{ secrets.STREAM_KEY }}
        STREAM_PATH: ${{ secrets.STREAM_PATH }}
      run: ./result/run
